/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 6

enum ts_symbol_identifiers {
  aux_sym_ntriplesDoc_token1 = 1,
  sym_comment = 2,
  anon_sym_VERSION = 3,
  anon_sym_DOT = 4,
  anon_sym_LT_LT_LPAREN = 5,
  anon_sym_RPAREN_GT_GT = 6,
  anon_sym_CARET_CARET = 7,
  anon_sym_AT = 8,
  anon_sym_DASH_DASH = 9,
  sym_LANGTAG = 10,
  sym_BASE_DIRECTION = 11,
  sym_IRIREF = 12,
  sym_BLANK_NODE_LABEL = 13,
  sym_STRING_LITERAL_QUOTE = 14,
  sym_ntriplesDoc = 15,
  sym_statement = 16,
  sym_directive = 17,
  sym_versionDirective = 18,
  sym_versionSpecifier = 19,
  sym_triple = 20,
  sym_subject = 21,
  sym_predicate = 22,
  sym_object = 23,
  sym_tripleTerm = 24,
  sym_literal = 25,
  sym__LANG_DIR = 26,
  aux_sym_ntriplesDoc_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_ntriplesDoc_token1] = "ntriplesDoc_token1",
  [sym_comment] = "comment",
  [anon_sym_VERSION] = "VERSION",
  [anon_sym_DOT] = ".",
  [anon_sym_LT_LT_LPAREN] = "<<(",
  [anon_sym_RPAREN_GT_GT] = ")>>",
  [anon_sym_CARET_CARET] = "^^",
  [anon_sym_AT] = "@",
  [anon_sym_DASH_DASH] = "--",
  [sym_LANGTAG] = "LANGTAG",
  [sym_BASE_DIRECTION] = "BASE_DIRECTION",
  [sym_IRIREF] = "IRIREF",
  [sym_BLANK_NODE_LABEL] = "BLANK_NODE_LABEL",
  [sym_STRING_LITERAL_QUOTE] = "STRING_LITERAL_QUOTE",
  [sym_ntriplesDoc] = "ntriplesDoc",
  [sym_statement] = "statement",
  [sym_directive] = "directive",
  [sym_versionDirective] = "versionDirective",
  [sym_versionSpecifier] = "versionSpecifier",
  [sym_triple] = "triple",
  [sym_subject] = "subject",
  [sym_predicate] = "predicate",
  [sym_object] = "object",
  [sym_tripleTerm] = "tripleTerm",
  [sym_literal] = "literal",
  [sym__LANG_DIR] = "_LANG_DIR",
  [aux_sym_ntriplesDoc_repeat1] = "ntriplesDoc_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_ntriplesDoc_token1] = aux_sym_ntriplesDoc_token1,
  [sym_comment] = sym_comment,
  [anon_sym_VERSION] = anon_sym_VERSION,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT_LT_LPAREN] = anon_sym_LT_LT_LPAREN,
  [anon_sym_RPAREN_GT_GT] = anon_sym_RPAREN_GT_GT,
  [anon_sym_CARET_CARET] = anon_sym_CARET_CARET,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [sym_LANGTAG] = sym_LANGTAG,
  [sym_BASE_DIRECTION] = sym_BASE_DIRECTION,
  [sym_IRIREF] = sym_IRIREF,
  [sym_BLANK_NODE_LABEL] = sym_BLANK_NODE_LABEL,
  [sym_STRING_LITERAL_QUOTE] = sym_STRING_LITERAL_QUOTE,
  [sym_ntriplesDoc] = sym_ntriplesDoc,
  [sym_statement] = sym_statement,
  [sym_directive] = sym_directive,
  [sym_versionDirective] = sym_versionDirective,
  [sym_versionSpecifier] = sym_versionSpecifier,
  [sym_triple] = sym_triple,
  [sym_subject] = sym_subject,
  [sym_predicate] = sym_predicate,
  [sym_object] = sym_object,
  [sym_tripleTerm] = sym_tripleTerm,
  [sym_literal] = sym_literal,
  [sym__LANG_DIR] = sym__LANG_DIR,
  [aux_sym_ntriplesDoc_repeat1] = aux_sym_ntriplesDoc_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_ntriplesDoc_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_VERSION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_LANGTAG] = {
    .visible = true,
    .named = true,
  },
  [sym_BASE_DIRECTION] = {
    .visible = true,
    .named = true,
  },
  [sym_IRIREF] = {
    .visible = true,
    .named = true,
  },
  [sym_BLANK_NODE_LABEL] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_ntriplesDoc] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_directive] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_versionDirective] = {
    .visible = true,
    .named = true,
  },
  [sym_versionSpecifier] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_triple] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_predicate] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_tripleTerm] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__LANG_DIR] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_ntriplesDoc_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_base_direction = 1,
  field_datatype_iri = 2,
  field_language_tag = 3,
  field_object = 4,
  field_predicate = 5,
  field_string = 6,
  field_subject = 7,
  field_versionSpecifier = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_base_direction] = "base_direction",
  [field_datatype_iri] = "datatype_iri",
  [field_language_tag] = "language_tag",
  [field_object] = "object",
  [field_predicate] = "predicate",
  [field_string] = "string",
  [field_subject] = "subject",
  [field_versionSpecifier] = "versionSpecifier",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 3},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_versionSpecifier, 1},
  [1] =
    {field_string, 0},
  [2] =
    {field_base_direction, 1, .inherited = true},
    {field_language_tag, 1, .inherited = true},
    {field_string, 0},
  [5] =
    {field_object, 2},
    {field_predicate, 1},
    {field_subject, 0},
  [8] =
    {field_datatype_iri, 2},
    {field_string, 0},
  [10] =
    {field_language_tag, 1},
  [11] =
    {field_object, 3},
    {field_predicate, 2},
    {field_subject, 1},
  [14] =
    {field_base_direction, 3},
    {field_language_tag, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_directive,
  sym_object,
  sym_predicate,
  sym_statement,
  sym_subject,
  sym_versionSpecifier,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_directive] = {.index = 0, .length = 1},
  [sym_object] = {.index = 1, .length = 4},
  [sym_predicate] = {.index = 5, .length = 1},
  [sym_statement] = {.index = 6, .length = 2},
  [sym_subject] = {.index = 8, .length = 2},
  [sym_versionSpecifier] = {.index = 10, .length = 1},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_versionDirective,
  [1] =
    sym_BLANK_NODE_LABEL,
    sym_IRIREF,
    sym_literal,
    sym_tripleTerm,
  [5] =
    sym_IRIREF,
  [6] =
    sym_directive,
    sym_triple,
  [8] =
    sym_BLANK_NODE_LABEL,
    sym_IRIREF,
  [10] =
    sym_STRING_LITERAL_QUOTE,
};

static const TSCharacterRange sym_BLANK_NODE_LABEL_character_set_1[] = {
  {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xc0, 0xd6}, {0xd8, 0xf6}, {0xf8, 0x2ff}, {0x370, 0x37d},
  {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf}, {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange sym_BLANK_NODE_LABEL_character_set_2[] = {
  {'-', '.'}, {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xb7, 0xb7}, {0xc0, 0xd6}, {0xd8, 0xf6},
  {0xf8, 0x37d}, {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x203f, 0x2040}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf},
  {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '"', 1,
        '#', 44,
        ')', 12,
        '-', 6,
        '.', 48,
        '<', 9,
        '@', 52,
        'V', 54,
        '^', 21,
        '_', 8,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(40);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(7);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_2, 18, lookahead)) ADVANCE(70);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '>') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != '^' &&
          lookahead != '`' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '^' &&
          lookahead != '`' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'I') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(45);
      END_STATE();
    case 16:
      if (lookahead == 'O') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'S') ADVANCE(14);
      END_STATE();
    case 19:
      ADVANCE_MAP(
        'U', 36,
        'u', 28,
        '"', 1,
        '\'', 1,
        '\\', 1,
        'b', 1,
        'f', 1,
        'n', 1,
        'r', 1,
        't', 1,
      );
      END_STATE();
    case 20:
      if (lookahead == 'U') ADVANCE(37);
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == '^') ADVANCE(51);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(1);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 39:
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_1, 16, lookahead)) ADVANCE(70);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '"', 1,
        '#', 44,
        ')', 12,
        '-', 6,
        '.', 48,
        '<', 9,
        '@', 52,
        'V', 62,
        '^', 21,
        '_', 8,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(40);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == 'V') ADVANCE(13);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(41);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_ntriplesDoc_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_VERSION);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_VERSION);
      if (lookahead == '-') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_VERSION);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_LT_LPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RPAREN_GT_GT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_CARET_CARET);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'E') ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'I') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'N') ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'O') ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'R') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'S') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'E') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'I') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'N') ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'O') ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'R') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (lookahead == 'S') ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_BASE_DIRECTION);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_IRIREF);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_BLANK_NODE_LABEL);
      if (lookahead == '.') ADVANCE(7);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_2, 18, lookahead)) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_STRING_LITERAL_QUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 41},
  [2] = {.lex_state = 41},
  [3] = {.lex_state = 41},
  [4] = {.lex_state = 41},
  [5] = {.lex_state = 41},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_ntriplesDoc_token1] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_VERSION] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT_LT_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN_GT_GT] = ACTIONS(1),
    [anon_sym_CARET_CARET] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [sym_LANGTAG] = ACTIONS(1),
    [sym_BASE_DIRECTION] = ACTIONS(1),
    [sym_IRIREF] = ACTIONS(1),
    [sym_BLANK_NODE_LABEL] = ACTIONS(1),
    [sym_STRING_LITERAL_QUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_ntriplesDoc] = STATE(25),
    [sym_statement] = STATE(13),
    [sym_directive] = STATE(29),
    [sym_versionDirective] = STATE(30),
    [sym_triple] = STATE(29),
    [sym_subject] = STATE(20),
    [aux_sym_ntriplesDoc_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_ntriplesDoc_token1] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_VERSION] = ACTIONS(9),
    [sym_IRIREF] = ACTIONS(11),
    [sym_BLANK_NODE_LABEL] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_VERSION,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_subject,
    STATE(27), 1,
      sym_statement,
    STATE(30), 1,
      sym_versionDirective,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(11), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(29), 2,
      sym_directive,
      sym_triple,
  [28] = 8,
    ACTIONS(9), 1,
      anon_sym_VERSION,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_subject,
    STATE(27), 1,
      sym_statement,
    STATE(30), 1,
      sym_versionDirective,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(11), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(29), 2,
      sym_directive,
      sym_triple,
  [56] = 8,
    ACTIONS(9), 1,
      anon_sym_VERSION,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_subject,
    STATE(27), 1,
      sym_statement,
    STATE(30), 1,
      sym_versionDirective,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(11), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(29), 2,
      sym_directive,
      sym_triple,
  [84] = 7,
    ACTIONS(9), 1,
      anon_sym_VERSION,
    STATE(20), 1,
      sym_subject,
    STATE(27), 1,
      sym_statement,
    STATE(30), 1,
      sym_versionDirective,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(11), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(29), 2,
      sym_directive,
      sym_triple,
  [109] = 6,
    ACTIONS(19), 1,
      anon_sym_LT_LT_LPAREN,
    ACTIONS(23), 1,
      sym_STRING_LITERAL_QUOTE,
    STATE(34), 1,
      sym_object,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(21), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(17), 2,
      sym_tripleTerm,
      sym_literal,
  [131] = 6,
    ACTIONS(19), 1,
      anon_sym_LT_LT_LPAREN,
    ACTIONS(23), 1,
      sym_STRING_LITERAL_QUOTE,
    STATE(36), 1,
      sym_object,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(21), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
    STATE(17), 2,
      sym_tripleTerm,
      sym_literal,
  [153] = 5,
    ACTIONS(27), 1,
      anon_sym_CARET_CARET,
    ACTIONS(29), 1,
      anon_sym_AT,
    STATE(22), 1,
      sym__LANG_DIR,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(25), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [171] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(31), 4,
      anon_sym_LT_LT_LPAREN,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
      sym_STRING_LITERAL_QUOTE,
  [182] = 3,
    STATE(21), 1,
      sym_subject,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(11), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [194] = 3,
    ACTIONS(35), 1,
      anon_sym_DASH_DASH,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(33), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [206] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      aux_sym_ntriplesDoc_token1,
    STATE(14), 1,
      aux_sym_ntriplesDoc_repeat1,
  [219] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      aux_sym_ntriplesDoc_token1,
    STATE(16), 1,
      aux_sym_ntriplesDoc_repeat1,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_ntriplesDoc_token1,
    STATE(14), 1,
      aux_sym_ntriplesDoc_repeat1,
  [245] = 3,
    ACTIONS(44), 1,
      sym_STRING_LITERAL_QUOTE,
    STATE(24), 1,
      sym_versionSpecifier,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      aux_sym_ntriplesDoc_token1,
    STATE(14), 1,
      aux_sym_ntriplesDoc_repeat1,
  [269] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(48), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [278] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(50), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [287] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(52), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [296] = 3,
    ACTIONS(54), 1,
      sym_IRIREF,
    STATE(7), 1,
      sym_predicate,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [307] = 3,
    ACTIONS(54), 1,
      sym_IRIREF,
    STATE(6), 1,
      sym_predicate,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [318] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(56), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [327] = 2,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
    ACTIONS(58), 2,
      anon_sym_DOT,
      anon_sym_RPAREN_GT_GT,
  [336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [344] = 2,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [352] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [368] = 2,
    ACTIONS(66), 1,
      sym_IRIREF,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [392] = 2,
    ACTIONS(72), 1,
      sym_LANGTAG,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      aux_sym_ntriplesDoc_token1,
  [408] = 2,
    ACTIONS(76), 1,
      sym_IRIREF,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [416] = 2,
    ACTIONS(78), 1,
      anon_sym_RPAREN_GT_GT,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [424] = 2,
    ACTIONS(80), 1,
      sym_BASE_DIRECTION,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
  [432] = 2,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      aux_sym_ntriplesDoc_token1,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 153,
  [SMALL_STATE(9)] = 171,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 194,
  [SMALL_STATE(12)] = 206,
  [SMALL_STATE(13)] = 219,
  [SMALL_STATE(14)] = 232,
  [SMALL_STATE(15)] = 245,
  [SMALL_STATE(16)] = 256,
  [SMALL_STATE(17)] = 269,
  [SMALL_STATE(18)] = 278,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 296,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 318,
  [SMALL_STATE(23)] = 327,
  [SMALL_STATE(24)] = 336,
  [SMALL_STATE(25)] = 344,
  [SMALL_STATE(26)] = 352,
  [SMALL_STATE(27)] = 360,
  [SMALL_STATE(28)] = 368,
  [SMALL_STATE(29)] = 376,
  [SMALL_STATE(30)] = 384,
  [SMALL_STATE(31)] = 392,
  [SMALL_STATE(32)] = 400,
  [SMALL_STATE(33)] = 408,
  [SMALL_STATE(34)] = 416,
  [SMALL_STATE(35)] = 424,
  [SMALL_STATE(36)] = 432,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ntriplesDoc, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ntriplesDoc, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ntriplesDoc, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ntriplesDoc, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__LANG_DIR, 2, 0, 6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ntriplesDoc_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ntriplesDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tripleTerm, 5, 0, 7),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 5),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2, 0, 3),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__LANG_DIR, 4, 0, 8),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versionDirective, 2, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versionSpecifier, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triple, 4, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ntriples(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ntriples",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
