/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 3

enum ts_symbol_identifiers {
  aux_sym_nquadsDoc_token1 = 1,
  sym_comment = 2,
  anon_sym_DOT = 3,
  anon_sym_CARET_CARET = 4,
  anon_sym_AT = 5,
  sym_LANGTAG = 6,
  sym_IRIREF = 7,
  sym_STRING_LITERAL_QUOTE = 8,
  sym_BLANK_NODE_LABEL = 9,
  sym_nquadsDoc = 10,
  sym_statement = 11,
  sym_subject = 12,
  sym_predicate = 13,
  sym_object = 14,
  sym_graphLabel = 15,
  sym_literal = 16,
  aux_sym_nquadsDoc_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_nquadsDoc_token1] = "nquadsDoc_token1",
  [sym_comment] = "comment",
  [anon_sym_DOT] = ".",
  [anon_sym_CARET_CARET] = "^^",
  [anon_sym_AT] = "@",
  [sym_LANGTAG] = "LANGTAG",
  [sym_IRIREF] = "IRIREF",
  [sym_STRING_LITERAL_QUOTE] = "STRING_LITERAL_QUOTE",
  [sym_BLANK_NODE_LABEL] = "BLANK_NODE_LABEL",
  [sym_nquadsDoc] = "nquadsDoc",
  [sym_statement] = "statement",
  [sym_subject] = "subject",
  [sym_predicate] = "predicate",
  [sym_object] = "object",
  [sym_graphLabel] = "graphLabel",
  [sym_literal] = "literal",
  [aux_sym_nquadsDoc_repeat1] = "nquadsDoc_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_nquadsDoc_token1] = aux_sym_nquadsDoc_token1,
  [sym_comment] = sym_comment,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_CARET_CARET] = anon_sym_CARET_CARET,
  [anon_sym_AT] = anon_sym_AT,
  [sym_LANGTAG] = sym_LANGTAG,
  [sym_IRIREF] = sym_IRIREF,
  [sym_STRING_LITERAL_QUOTE] = sym_STRING_LITERAL_QUOTE,
  [sym_BLANK_NODE_LABEL] = sym_BLANK_NODE_LABEL,
  [sym_nquadsDoc] = sym_nquadsDoc,
  [sym_statement] = sym_statement,
  [sym_subject] = sym_subject,
  [sym_predicate] = sym_predicate,
  [sym_object] = sym_object,
  [sym_graphLabel] = sym_graphLabel,
  [sym_literal] = sym_literal,
  [aux_sym_nquadsDoc_repeat1] = aux_sym_nquadsDoc_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_nquadsDoc_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_LANGTAG] = {
    .visible = true,
    .named = true,
  },
  [sym_IRIREF] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_BLANK_NODE_LABEL] = {
    .visible = true,
    .named = true,
  },
  [sym_nquadsDoc] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_predicate] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_graphLabel] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_nquadsDoc_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_datatype_iri = 1,
  field_graphLabel = 2,
  field_language_tag = 3,
  field_object = 4,
  field_predicate = 5,
  field_string = 6,
  field_subject = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_datatype_iri] = "datatype_iri",
  [field_graphLabel] = "graphLabel",
  [field_language_tag] = "language_tag",
  [field_object] = "object",
  [field_predicate] = "predicate",
  [field_string] = "string",
  [field_subject] = "subject",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_string, 0},
  [1] =
    {field_object, 2},
    {field_predicate, 1},
    {field_subject, 0},
  [4] =
    {field_datatype_iri, 2},
    {field_string, 0},
  [6] =
    {field_language_tag, 2},
    {field_string, 0},
  [8] =
    {field_graphLabel, 3},
    {field_object, 2},
    {field_predicate, 1},
    {field_subject, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_object,
  sym_predicate,
  sym_subject,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_object] = {.index = 0, .length = 3},
  [sym_predicate] = {.index = 3, .length = 1},
  [sym_subject] = {.index = 4, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_BLANK_NODE_LABEL,
    sym_IRIREF,
    sym_literal,
  [3] =
    sym_IRIREF,
  [4] =
    sym_BLANK_NODE_LABEL,
    sym_IRIREF,
};

static const TSCharacterRange sym_BLANK_NODE_LABEL_character_set_1[] = {
  {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xc0, 0xd6}, {0xd8, 0xf6}, {0xf8, 0x2ff}, {0x370, 0x37d},
  {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf}, {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange sym_BLANK_NODE_LABEL_character_set_2[] = {
  {'-', '.'}, {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xb7, 0xb7}, {0xc0, 0xd6}, {0xd8, 0xf6},
  {0xf8, 0x37d}, {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x203f, 0x2040}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf},
  {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '^') ADVANCE(7);
      if (lookahead == '_') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(26);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(2);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_2, 18, lookahead)) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '^' &&
          lookahead != '`' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        'U', 22,
        'u', 14,
        '"', 1,
        '\'', 1,
        '\\', 1,
        'b', 1,
        'f', 1,
        'n', 1,
        'r', 1,
        't', 1,
      );
      END_STATE();
    case 6:
      if (lookahead == 'U') ADVANCE(23);
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '^') ADVANCE(31);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(1);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 25:
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_1, 16, lookahead)) ADVANCE(37);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '^') ADVANCE(7);
      if (lookahead == '_') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(26);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_nquadsDoc_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_CARET_CARET);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_IRIREF);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_STRING_LITERAL_QUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_BLANK_NODE_LABEL);
      if (lookahead == '.') ADVANCE(2);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_2, 18, lookahead)) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_nquadsDoc_token1] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_CARET_CARET] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_LANGTAG] = ACTIONS(1),
    [sym_IRIREF] = ACTIONS(1),
    [sym_STRING_LITERAL_QUOTE] = ACTIONS(1),
    [sym_BLANK_NODE_LABEL] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_nquadsDoc] = STATE(20),
    [sym_statement] = STATE(14),
    [sym_subject] = STATE(13),
    [aux_sym_nquadsDoc_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_nquadsDoc_token1] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_IRIREF] = ACTIONS(9),
    [sym_BLANK_NODE_LABEL] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_subject,
    STATE(19), 1,
      sym_statement,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(9), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [18] = 5,
    ACTIONS(15), 1,
      sym_STRING_LITERAL_QUOTE,
    STATE(7), 1,
      sym_object,
    STATE(10), 1,
      sym_literal,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(13), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [36] = 5,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_subject,
    STATE(19), 1,
      sym_statement,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(9), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [54] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_subject,
    STATE(19), 1,
      sym_statement,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(9), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [72] = 4,
    ACTIONS(23), 1,
      anon_sym_CARET_CARET,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(21), 3,
      anon_sym_DOT,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [88] = 4,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(25), 1,
      sym_graphLabel,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(29), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [103] = 4,
    STATE(13), 1,
      sym_subject,
    STATE(19), 1,
      sym_statement,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(9), 2,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [118] = 2,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(31), 3,
      sym_IRIREF,
      sym_STRING_LITERAL_QUOTE,
      sym_BLANK_NODE_LABEL,
  [128] = 2,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(33), 3,
      anon_sym_DOT,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [138] = 2,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(35), 3,
      anon_sym_DOT,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [148] = 2,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
    ACTIONS(37), 3,
      anon_sym_DOT,
      sym_IRIREF,
      sym_BLANK_NODE_LABEL,
  [158] = 3,
    ACTIONS(39), 1,
      sym_IRIREF,
    STATE(3), 1,
      sym_predicate,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [169] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_nquadsDoc_token1,
    STATE(16), 1,
      aux_sym_nquadsDoc_repeat1,
  [182] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_nquadsDoc_token1,
    STATE(17), 1,
      aux_sym_nquadsDoc_repeat1,
  [195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      aux_sym_nquadsDoc_token1,
    STATE(17), 1,
      aux_sym_nquadsDoc_repeat1,
  [208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      aux_sym_nquadsDoc_token1,
    STATE(17), 1,
      aux_sym_nquadsDoc_repeat1,
  [221] = 2,
    ACTIONS(50), 1,
      sym_IRIREF,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      aux_sym_nquadsDoc_token1,
  [237] = 2,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [245] = 2,
    ACTIONS(54), 1,
      sym_LANGTAG,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [253] = 2,
    ACTIONS(56), 1,
      sym_IRIREF,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [261] = 2,
    ACTIONS(58), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      aux_sym_nquadsDoc_token1,
  [277] = 2,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      aux_sym_nquadsDoc_token1,
      sym_comment,
  [285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_nquadsDoc_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 88,
  [SMALL_STATE(8)] = 103,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 138,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 158,
  [SMALL_STATE(14)] = 169,
  [SMALL_STATE(15)] = 182,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 208,
  [SMALL_STATE(18)] = 221,
  [SMALL_STATE(19)] = 229,
  [SMALL_STATE(20)] = 237,
  [SMALL_STATE(21)] = 245,
  [SMALL_STATE(22)] = 253,
  [SMALL_STATE(23)] = 261,
  [SMALL_STATE(24)] = 269,
  [SMALL_STATE(25)] = 277,
  [SMALL_STATE(26)] = 285,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nquadsDoc, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nquadsDoc, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nquadsDoc, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nquadsDoc, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nquadsDoc_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nquadsDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_graphLabel, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 5, 0, 5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nquads(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nquads",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
