/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 1
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 10

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_DOT = 2,
  anon_sym_ATprefix = 3,
  aux_sym__prefixID_token1 = 4,
  anon_sym_ATbase = 5,
  aux_sym__sparqlPrefix_token1 = 6,
  aux_sym__sparqlBase_token1 = 7,
  anon_sym_SEMI = 8,
  anon_sym_COMMA = 9,
  anon_sym_a = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_CARET_CARET = 15,
  anon_sym_AT = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_IRIREF = 19,
  sym__PNAME_LN = 20,
  sym_BLANK_NODE_LABEL = 21,
  sym_LANGTAG = 22,
  sym_INTEGER = 23,
  sym_DECIMAL = 24,
  sym_DOUBLE = 25,
  sym_STRING_LITERAL_QUOTE = 26,
  sym_STRING_LITERAL_SINGLE_QUOTE = 27,
  sym_STRING_LITERAL_LONG_SINGLE_QUOTE = 28,
  sym_STRING_LITERAL_LONG_QUOTE = 29,
  sym_ANON = 30,
  sym_turtleDoc = 31,
  sym_statement = 32,
  sym_directive = 33,
  sym__prefixID = 34,
  sym_base = 35,
  sym__base = 36,
  sym_prefix = 37,
  sym__sparqlPrefix = 38,
  sym__sparqlBase = 39,
  sym_triples = 40,
  sym_predicateObjectList = 41,
  sym_objectList = 42,
  sym_verb = 43,
  sym_subject = 44,
  sym_predicate = 45,
  sym_object = 46,
  sym_literal = 47,
  sym_blankNodePropertyList = 48,
  sym_collection = 49,
  sym_NumericLiteral = 50,
  sym_RDFLiteral = 51,
  sym_BooleanLiteral = 52,
  sym_String = 53,
  sym_iri = 54,
  sym_PrefixedName = 55,
  sym_BlankNode = 56,
  aux_sym_turtleDoc_repeat1 = 57,
  aux_sym_predicateObjectList_repeat1 = 58,
  aux_sym_objectList_repeat1 = 59,
  aux_sym_collection_repeat1 = 60,
  alias_sym_PNAME_NS = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_DOT] = ".",
  [anon_sym_ATprefix] = "@prefix",
  [aux_sym__prefixID_token1] = "_prefixID_token1",
  [anon_sym_ATbase] = "@base",
  [aux_sym__sparqlPrefix_token1] = "PREFIX",
  [aux_sym__sparqlBase_token1] = "BASE",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_a] = "a",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_CARET_CARET] = "^^",
  [anon_sym_AT] = "@",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_IRIREF] = "IRIREF",
  [sym__PNAME_LN] = "_PNAME_LN",
  [sym_BLANK_NODE_LABEL] = "BLANK_NODE_LABEL",
  [sym_LANGTAG] = "LANGTAG",
  [sym_INTEGER] = "INTEGER",
  [sym_DECIMAL] = "DECIMAL",
  [sym_DOUBLE] = "DOUBLE",
  [sym_STRING_LITERAL_QUOTE] = "STRING_LITERAL_QUOTE",
  [sym_STRING_LITERAL_SINGLE_QUOTE] = "STRING_LITERAL_SINGLE_QUOTE",
  [sym_STRING_LITERAL_LONG_SINGLE_QUOTE] = "STRING_LITERAL_LONG_SINGLE_QUOTE",
  [sym_STRING_LITERAL_LONG_QUOTE] = "STRING_LITERAL_LONG_QUOTE",
  [sym_ANON] = "ANON",
  [sym_turtleDoc] = "turtleDoc",
  [sym_statement] = "statement",
  [sym_directive] = "directive",
  [sym__prefixID] = "_prefixID",
  [sym_base] = "base",
  [sym__base] = "_base",
  [sym_prefix] = "prefix",
  [sym__sparqlPrefix] = "_sparqlPrefix",
  [sym__sparqlBase] = "_sparqlBase",
  [sym_triples] = "triples",
  [sym_predicateObjectList] = "predicateObjectList",
  [sym_objectList] = "objectList",
  [sym_verb] = "verb",
  [sym_subject] = "subject",
  [sym_predicate] = "predicate",
  [sym_object] = "object",
  [sym_literal] = "literal",
  [sym_blankNodePropertyList] = "blankNodePropertyList",
  [sym_collection] = "collection",
  [sym_NumericLiteral] = "NumericLiteral",
  [sym_RDFLiteral] = "RDFLiteral",
  [sym_BooleanLiteral] = "BooleanLiteral",
  [sym_String] = "String",
  [sym_iri] = "iri",
  [sym_PrefixedName] = "PrefixedName",
  [sym_BlankNode] = "BlankNode",
  [aux_sym_turtleDoc_repeat1] = "turtleDoc_repeat1",
  [aux_sym_predicateObjectList_repeat1] = "predicateObjectList_repeat1",
  [aux_sym_objectList_repeat1] = "objectList_repeat1",
  [aux_sym_collection_repeat1] = "collection_repeat1",
  [alias_sym_PNAME_NS] = "PNAME_NS",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATprefix] = anon_sym_ATprefix,
  [aux_sym__prefixID_token1] = aux_sym__prefixID_token1,
  [anon_sym_ATbase] = anon_sym_ATbase,
  [aux_sym__sparqlPrefix_token1] = aux_sym__sparqlPrefix_token1,
  [aux_sym__sparqlBase_token1] = aux_sym__sparqlBase_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_CARET_CARET] = anon_sym_CARET_CARET,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_IRIREF] = sym_IRIREF,
  [sym__PNAME_LN] = sym__PNAME_LN,
  [sym_BLANK_NODE_LABEL] = sym_BLANK_NODE_LABEL,
  [sym_LANGTAG] = sym_LANGTAG,
  [sym_INTEGER] = sym_INTEGER,
  [sym_DECIMAL] = sym_DECIMAL,
  [sym_DOUBLE] = sym_DOUBLE,
  [sym_STRING_LITERAL_QUOTE] = sym_STRING_LITERAL_QUOTE,
  [sym_STRING_LITERAL_SINGLE_QUOTE] = sym_STRING_LITERAL_SINGLE_QUOTE,
  [sym_STRING_LITERAL_LONG_SINGLE_QUOTE] = sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
  [sym_STRING_LITERAL_LONG_QUOTE] = sym_STRING_LITERAL_LONG_QUOTE,
  [sym_ANON] = sym_ANON,
  [sym_turtleDoc] = sym_turtleDoc,
  [sym_statement] = sym_statement,
  [sym_directive] = sym_directive,
  [sym__prefixID] = sym__prefixID,
  [sym_base] = sym_base,
  [sym__base] = sym__base,
  [sym_prefix] = sym_prefix,
  [sym__sparqlPrefix] = sym__sparqlPrefix,
  [sym__sparqlBase] = sym__sparqlBase,
  [sym_triples] = sym_triples,
  [sym_predicateObjectList] = sym_predicateObjectList,
  [sym_objectList] = sym_objectList,
  [sym_verb] = sym_verb,
  [sym_subject] = sym_subject,
  [sym_predicate] = sym_predicate,
  [sym_object] = sym_object,
  [sym_literal] = sym_literal,
  [sym_blankNodePropertyList] = sym_blankNodePropertyList,
  [sym_collection] = sym_collection,
  [sym_NumericLiteral] = sym_NumericLiteral,
  [sym_RDFLiteral] = sym_RDFLiteral,
  [sym_BooleanLiteral] = sym_BooleanLiteral,
  [sym_String] = sym_String,
  [sym_iri] = sym_iri,
  [sym_PrefixedName] = sym_PrefixedName,
  [sym_BlankNode] = sym_BlankNode,
  [aux_sym_turtleDoc_repeat1] = aux_sym_turtleDoc_repeat1,
  [aux_sym_predicateObjectList_repeat1] = aux_sym_predicateObjectList_repeat1,
  [aux_sym_objectList_repeat1] = aux_sym_objectList_repeat1,
  [aux_sym_collection_repeat1] = aux_sym_collection_repeat1,
  [alias_sym_PNAME_NS] = alias_sym_PNAME_NS,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATprefix] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__prefixID_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ATbase] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__sparqlPrefix_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__sparqlBase_token1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_IRIREF] = {
    .visible = true,
    .named = true,
  },
  [sym__PNAME_LN] = {
    .visible = false,
    .named = true,
  },
  [sym_BLANK_NODE_LABEL] = {
    .visible = true,
    .named = true,
  },
  [sym_LANGTAG] = {
    .visible = true,
    .named = true,
  },
  [sym_INTEGER] = {
    .visible = true,
    .named = true,
  },
  [sym_DECIMAL] = {
    .visible = true,
    .named = true,
  },
  [sym_DOUBLE] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_SINGLE_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_LONG_SINGLE_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_STRING_LITERAL_LONG_QUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_ANON] = {
    .visible = true,
    .named = true,
  },
  [sym_turtleDoc] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__prefixID] = {
    .visible = false,
    .named = true,
  },
  [sym_base] = {
    .visible = true,
    .named = true,
  },
  [sym__base] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym__sparqlPrefix] = {
    .visible = false,
    .named = true,
  },
  [sym__sparqlBase] = {
    .visible = false,
    .named = true,
  },
  [sym_triples] = {
    .visible = true,
    .named = true,
  },
  [sym_predicateObjectList] = {
    .visible = true,
    .named = true,
  },
  [sym_objectList] = {
    .visible = true,
    .named = true,
  },
  [sym_verb] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_subject] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_predicate] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_blankNodePropertyList] = {
    .visible = true,
    .named = true,
  },
  [sym_collection] = {
    .visible = true,
    .named = true,
  },
  [sym_NumericLiteral] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_RDFLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_BooleanLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_String] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_iri] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_PrefixedName] = {
    .visible = true,
    .named = true,
  },
  [sym_BlankNode] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_turtleDoc_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_predicateObjectList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_objectList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_collection_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_PNAME_NS] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_datatype_iri = 1,
  field_iri = 2,
  field_language_tag = 3,
  field_object = 4,
  field_predicate = 5,
  field_prefix_label = 6,
  field_string = 7,
  field_subject = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_datatype_iri] = "datatype_iri",
  [field_iri] = "iri",
  [field_language_tag] = "language_tag",
  [field_object] = "object",
  [field_predicate] = "predicate",
  [field_prefix_label] = "prefix_label",
  [field_string] = "string",
  [field_subject] = "subject",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 1},
  [15] = {.index = 21, .length = 2},
  [16] = {.index = 23, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_iri, 0, .inherited = true},
    {field_prefix_label, 0, .inherited = true},
  [2] =
    {field_iri, 0, .inherited = true},
  [3] =
    {field_iri, 1},
  [4] =
    {field_string, 0},
  [5] =
    {field_subject, 0},
  [6] =
    {field_iri, 2},
    {field_prefix_label, 1},
  [8] =
    {field_predicate, 0},
  [9] =
    {field_object, 0},
  [10] =
    {field_predicate, 0},
    {field_predicate, 2, .inherited = true},
  [12] =
    {field_object, 0},
    {field_object, 1, .inherited = true},
  [14] =
    {field_datatype_iri, 2},
    {field_string, 0},
  [16] =
    {field_language_tag, 2},
    {field_string, 0},
  [18] =
    {field_predicate, 0, .inherited = true},
    {field_predicate, 1, .inherited = true},
  [20] =
    {field_object, 1},
  [21] =
    {field_object, 0, .inherited = true},
    {field_object, 1, .inherited = true},
  [23] =
    {field_predicate, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [6] = {
    [1] = alias_sym_PNAME_NS,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_BlankNode,
  sym_NumericLiteral,
  sym_String,
  sym_directive,
  sym_iri,
  sym_literal,
  sym_object,
  sym_predicate,
  sym_subject,
  sym_verb,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_BlankNode] = {.index = 0, .length = 2},
  [sym_NumericLiteral] = {.index = 2, .length = 3},
  [sym_String] = {.index = 5, .length = 4},
  [sym_directive] = {.index = 9, .length = 2},
  [sym_iri] = {.index = 11, .length = 2},
  [sym_literal] = {.index = 13, .length = 3},
  [sym_object] = {.index = 16, .length = 5},
  [sym_predicate] = {.index = 21, .length = 1},
  [sym_subject] = {.index = 22, .length = 3},
  [sym_verb] = {.index = 25, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_ANON,
    sym_BLANK_NODE_LABEL,
  [2] =
    sym_DECIMAL,
    sym_DOUBLE,
    sym_INTEGER,
  [5] =
    sym_STRING_LITERAL_LONG_QUOTE,
    sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
    sym_STRING_LITERAL_QUOTE,
    sym_STRING_LITERAL_SINGLE_QUOTE,
  [9] =
    sym_base,
    sym_prefix,
  [11] =
    sym_IRIREF,
    sym_PrefixedName,
  [13] =
    sym_BooleanLiteral,
    sym_NumericLiteral,
    sym_RDFLiteral,
  [16] =
    sym_BlankNode,
    sym_blankNodePropertyList,
    sym_collection,
    sym_iri,
    sym_literal,
  [21] =
    sym_iri,
  [22] =
    sym_BlankNode,
    sym_collection,
    sym_iri,
  [25] =
    anon_sym_a,
    sym_predicate,
};

static const TSCharacterRange aux_sym__prefixID_token1_character_set_1[] = {
  {':', ':'}, {'A', 'Z'}, {'a', 'z'}, {0xc0, 0xd6}, {0xd8, 0xf6}, {0xf8, 0x2ff}, {0x370, 0x37d}, {0x37f, 0x1fff},
  {0x200c, 0x200d}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf}, {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange aux_sym__prefixID_token1_character_set_3[] = {
  {'-', '.'}, {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xb7, 0xb7}, {0xc0, 0xd6}, {0xd8, 0xf6},
  {0xf8, 0x37d}, {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x203f, 0x2040}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf},
  {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange sym__PNAME_LN_character_set_1[] = {
  {'%', '%'}, {'0', ':'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0xc0, 0xd6}, {0xd8, 0xf6},
  {0xf8, 0x2ff}, {0x370, 0x37d}, {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf},
  {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange sym__PNAME_LN_character_set_2[] = {
  {'%', '%'}, {'-', '.'}, {'0', ':'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0xb7, 0xb7},
  {0xc0, 0xd6}, {0xd8, 0xf6}, {0xf8, 0x37d}, {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x203f, 0x2040}, {0x2070, 0x218f}, {0x2c00, 0x2fef},
  {0x3001, 0xd7ff}, {0xf900, 0xfdcf}, {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static const TSCharacterRange sym_BLANK_NODE_LABEL_character_set_1[] = {
  {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xc0, 0xd6}, {0xd8, 0xf6}, {0xf8, 0x2ff}, {0x370, 0x37d},
  {0x37f, 0x1fff}, {0x200c, 0x200d}, {0x2070, 0x218f}, {0x2c00, 0x2fef}, {0x3001, 0xd7ff}, {0xf900, 0xfdcf}, {0xfdf0, 0xfffd}, {0x10000, 0xeffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(105);
      ADVANCE_MAP(
        '"', 1,
        '#', 106,
        '\'', 11,
        '(', 120,
        ')', 121,
        ',', 116,
        '.', 108,
        ':', 111,
        ';', 115,
        '<', 38,
        '@', 123,
        '[', 118,
        ']', 119,
        '^', 45,
        '_', 37,
        'a', 117,
        'f', 16,
        't', 20,
        '+', 33,
        '-', 33,
        'B', 23,
        'b', 23,
        'P', 28,
        'p', 28,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_1, 16, lookahead)) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(135);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(139);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '#', 106,
        ',', 116,
        '.', 107,
        ':', 111,
        ';', 115,
        '<', 38,
        ']', 119,
        'a', 117,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      if (set_contains(aux_sym__prefixID_token1_character_set_1, 15, lookahead)) ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(106);
      if (lookahead == ':') ADVANCE(110);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      if (set_contains(aux_sym__prefixID_token1_character_set_1, 15, lookahead)) ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 10:
      if (lookahead == '%') ADVANCE(66);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(59);
      if (set_contains(sym__PNAME_LN_character_set_2, 20, lookahead)) ADVANCE(127);
      END_STATE();
    case 11:
      if (lookahead == '\'') ADVANCE(137);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '\'') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '\'') ADVANCE(138);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '\'') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'a') ADVANCE(19);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'e') ADVANCE(124);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'e') ADVANCE(125);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'l') ADVANCE(21);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'r') ADVANCE(22);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 's') ADVANCE(18);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'u') ADVANCE(17);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(29);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(114);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(27);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(30);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(24);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(25);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 30:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(113);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 31:
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 32:
      if (lookahead == '.') ADVANCE(32);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 34:
      if (lookahead == '.') ADVANCE(34);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(128);
      END_STATE();
    case 35:
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == ':') ADVANCE(110);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(35);
      END_STATE();
    case 36:
      if (lookahead == '.') ADVANCE(36);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(35);
      END_STATE();
    case 37:
      if (lookahead == ':') ADVANCE(103);
      END_STATE();
    case 38:
      if (lookahead == '>') ADVANCE(126);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '^' &&
          lookahead != '`' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ADVANCE_MAP(
        'U', 97,
        'u', 77,
        '"', 2,
        '\'', 2,
        '\\', 2,
        'b', 2,
        'f', 2,
        'n', 2,
        'r', 2,
        't', 2,
      );
      END_STATE();
    case 40:
      ADVANCE_MAP(
        'U', 98,
        'u', 78,
        '"', 12,
        '\'', 12,
        '\\', 12,
        'b', 12,
        'f', 12,
        'n', 12,
        'r', 12,
        't', 12,
      );
      END_STATE();
    case 41:
      if (lookahead == 'U') ADVANCE(99);
      if (lookahead == 'u') ADVANCE(79);
      END_STATE();
    case 42:
      ADVANCE_MAP(
        'U', 100,
        'u', 80,
        '"', 5,
        '\'', 5,
        '\\', 5,
        'b', 5,
        'f', 5,
        'n', 5,
        'r', 5,
        't', 5,
      );
      END_STATE();
    case 43:
      ADVANCE_MAP(
        'U', 101,
        'u', 81,
        '"', 15,
        '\'', 15,
        '\\', 15,
        'b', 15,
        'f', 15,
        'n', 15,
        'r', 15,
        't', 15,
      );
      END_STATE();
    case 44:
      if (lookahead == ']') ADVANCE(140);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      if (lookahead == '^') ADVANCE(122);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'b') ADVANCE(46);
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 50:
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 54:
      if (lookahead == 'x') ADVANCE(109);
      END_STATE();
    case 55:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 56:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 59:
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '/') ||
          lookahead == ';' ||
          lookahead == '=' ||
          lookahead == '?' ||
          lookahead == '@' ||
          lookahead == '_' ||
          lookahead == '~') ADVANCE(127);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(127);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(2);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(63);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 73:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 74:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      END_STATE();
    case 84:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 85:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 86:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 87:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 88:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 89:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(84);
      END_STATE();
    case 90:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 91:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 92:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 93:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 94:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(89);
      END_STATE();
    case 95:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      END_STATE();
    case 96:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      END_STATE();
    case 97:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(92);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(93);
      END_STATE();
    case 99:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      END_STATE();
    case 100:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(95);
      END_STATE();
    case 101:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(96);
      END_STATE();
    case 102:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(130);
      END_STATE();
    case 103:
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_1, 16, lookahead)) ADVANCE(128);
      END_STATE();
    case 104:
      if (eof) ADVANCE(105);
      ADVANCE_MAP(
        '"', 1,
        '#', 106,
        '\'', 11,
        '(', 120,
        ')', 121,
        '.', 57,
        ':', 111,
        '<', 38,
        '@', 47,
        '[', 118,
        '_', 37,
        'f', 16,
        't', 20,
        '+', 33,
        '-', 33,
        'B', 23,
        'b', 23,
        'P', 28,
        'p', 28,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(104);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (set_contains(sym_BLANK_NODE_LABEL_character_set_1, 16, lookahead)) ADVANCE(31);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_ATprefix);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym__prefixID_token1);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym__prefixID_token1);
      if (lookahead == '%') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(59);
      if (set_contains(sym__PNAME_LN_character_set_1, 18, lookahead)) ADVANCE(127);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_ATbase);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym__sparqlPrefix_token1);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym__sparqlBase_token1);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_a);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(140);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_CARET_CARET);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(111);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(31);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_IRIREF);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym__PNAME_LN);
      if (lookahead == '%') ADVANCE(66);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(59);
      if (set_contains(sym__PNAME_LN_character_set_2, 20, lookahead)) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_BLANK_NODE_LABEL);
      if (lookahead == '.') ADVANCE(34);
      if (set_contains(aux_sym__prefixID_token1_character_set_3, 18, lookahead)) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(102);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_LANGTAG);
      if (lookahead == '-') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_INTEGER);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_DECIMAL);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_DOUBLE);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_STRING_LITERAL_QUOTE);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_STRING_LITERAL_QUOTE);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_STRING_LITERAL_SINGLE_QUOTE);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_STRING_LITERAL_SINGLE_QUOTE);
      if (lookahead == '\'') ADVANCE(15);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_STRING_LITERAL_LONG_SINGLE_QUOTE);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_STRING_LITERAL_LONG_QUOTE);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_ANON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 104},
  [2] = {.lex_state = 104},
  [3] = {.lex_state = 104},
  [4] = {.lex_state = 104},
  [5] = {.lex_state = 104},
  [6] = {.lex_state = 104},
  [7] = {.lex_state = 104},
  [8] = {.lex_state = 104},
  [9] = {.lex_state = 104},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 104},
  [25] = {.lex_state = 104},
  [26] = {.lex_state = 104},
  [27] = {.lex_state = 104},
  [28] = {.lex_state = 104},
  [29] = {.lex_state = 104},
  [30] = {.lex_state = 104},
  [31] = {.lex_state = 104},
  [32] = {.lex_state = 104},
  [33] = {.lex_state = 104},
  [34] = {.lex_state = 104},
  [35] = {.lex_state = 104},
  [36] = {.lex_state = 104},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym__prefixID_token1] = ACTIONS(1),
    [aux_sym__sparqlPrefix_token1] = ACTIONS(1),
    [aux_sym__sparqlBase_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_CARET_CARET] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_IRIREF] = ACTIONS(1),
    [sym__PNAME_LN] = ACTIONS(1),
    [sym_BLANK_NODE_LABEL] = ACTIONS(1),
    [sym_INTEGER] = ACTIONS(1),
    [sym_DECIMAL] = ACTIONS(1),
    [sym_DOUBLE] = ACTIONS(1),
    [sym_STRING_LITERAL_QUOTE] = ACTIONS(1),
    [sym_STRING_LITERAL_SINGLE_QUOTE] = ACTIONS(1),
    [sym_STRING_LITERAL_LONG_SINGLE_QUOTE] = ACTIONS(1),
    [sym_STRING_LITERAL_LONG_QUOTE] = ACTIONS(1),
    [sym_ANON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_turtleDoc] = STATE(60),
    [sym_statement] = STATE(6),
    [sym_directive] = STATE(27),
    [sym__prefixID] = STATE(30),
    [sym_base] = STATE(31),
    [sym__base] = STATE(36),
    [sym_prefix] = STATE(31),
    [sym__sparqlPrefix] = STATE(33),
    [sym__sparqlBase] = STATE(35),
    [sym_triples] = STATE(61),
    [sym_subject] = STATE(40),
    [sym_blankNodePropertyList] = STATE(38),
    [sym_collection] = STATE(48),
    [sym_iri] = STATE(48),
    [sym_PrefixedName] = STATE(13),
    [sym_BlankNode] = STATE(48),
    [aux_sym_turtleDoc_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_ATprefix] = ACTIONS(7),
    [aux_sym__prefixID_token1] = ACTIONS(9),
    [anon_sym_ATbase] = ACTIONS(11),
    [aux_sym__sparqlPrefix_token1] = ACTIONS(13),
    [aux_sym__sparqlBase_token1] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_IRIREF] = ACTIONS(21),
    [sym__PNAME_LN] = ACTIONS(23),
    [sym_BLANK_NODE_LABEL] = ACTIONS(25),
    [sym_ANON] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      sym_DOUBLE,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(35), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(37), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(3), 2,
      sym_object,
      aux_sym_collection_repeat1,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [67] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(33), 1,
      sym_DOUBLE,
    ACTIONS(39), 1,
      anon_sym_RPAREN,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(35), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(37), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(4), 2,
      sym_object,
      aux_sym_collection_repeat1,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [134] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      aux_sym__prefixID_token1,
    ACTIONS(44), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      sym_IRIREF,
    ACTIONS(58), 1,
      sym__PNAME_LN,
    ACTIONS(67), 1,
      sym_DOUBLE,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    ACTIONS(52), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(61), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(64), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(70), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(73), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(4), 2,
      sym_object,
      aux_sym_collection_repeat1,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [201] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(33), 1,
      sym_DOUBLE,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(41), 1,
      sym_object,
    STATE(45), 1,
      sym_objectList,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(35), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(37), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [267] = 24,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_ATprefix,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(11), 1,
      anon_sym_ATbase,
    ACTIONS(13), 1,
      aux_sym__sparqlPrefix_token1,
    ACTIONS(15), 1,
      aux_sym__sparqlBase_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(27), 1,
      sym_directive,
    STATE(30), 1,
      sym__prefixID,
    STATE(33), 1,
      sym__sparqlPrefix,
    STATE(35), 1,
      sym__sparqlBase,
    STATE(36), 1,
      sym__base,
    STATE(38), 1,
      sym_blankNodePropertyList,
    STATE(40), 1,
      sym_subject,
    STATE(61), 1,
      sym_triples,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    STATE(7), 2,
      sym_statement,
      aux_sym_turtleDoc_repeat1,
    STATE(31), 2,
      sym_base,
      sym_prefix,
    STATE(48), 3,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [345] = 24,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_ATprefix,
    ACTIONS(83), 1,
      aux_sym__prefixID_token1,
    ACTIONS(86), 1,
      anon_sym_ATbase,
    ACTIONS(89), 1,
      aux_sym__sparqlPrefix_token1,
    ACTIONS(92), 1,
      aux_sym__sparqlBase_token1,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      sym_IRIREF,
    ACTIONS(104), 1,
      sym__PNAME_LN,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(27), 1,
      sym_directive,
    STATE(30), 1,
      sym__prefixID,
    STATE(33), 1,
      sym__sparqlPrefix,
    STATE(35), 1,
      sym__sparqlBase,
    STATE(36), 1,
      sym__base,
    STATE(38), 1,
      sym_blankNodePropertyList,
    STATE(40), 1,
      sym_subject,
    STATE(61), 1,
      sym_triples,
    ACTIONS(107), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    STATE(7), 2,
      sym_statement,
      aux_sym_turtleDoc_repeat1,
    STATE(31), 2,
      sym_base,
      sym_prefix,
    STATE(48), 3,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [423] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(33), 1,
      sym_DOUBLE,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(41), 1,
      sym_object,
    STATE(50), 1,
      sym_objectList,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(35), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(37), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [489] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(33), 1,
      sym_DOUBLE,
    STATE(11), 1,
      sym_String,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(49), 1,
      sym_object,
    ACTIONS(25), 2,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_INTEGER,
      sym_DECIMAL,
    ACTIONS(35), 2,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(37), 2,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
    STATE(22), 3,
      sym_NumericLiteral,
      sym_RDFLiteral,
      sym_BooleanLiteral,
    STATE(21), 5,
      sym_literal,
      sym_blankNodePropertyList,
      sym_collection,
      sym_iri,
      sym_BlankNode,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(112), 14,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_CARET_CARET,
      anon_sym_AT,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [583] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_CARET_CARET,
    ACTIONS(120), 1,
      anon_sym_AT,
    ACTIONS(114), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(116), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(124), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(128), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(132), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [708] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(136), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(140), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 10,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_a,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(144), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [798] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(148), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(152), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [856] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(156), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [885] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(160), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [914] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(164), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [943] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 9,
      anon_sym_DOT,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(168), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [972] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 8,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(172), 8,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [996] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 8,
      aux_sym__prefixID_token1,
      anon_sym_LBRACK,
      anon_sym_true,
      anon_sym_false,
      sym_INTEGER,
      sym_DECIMAL,
      sym_STRING_LITERAL_QUOTE,
      sym_STRING_LITERAL_SINGLE_QUOTE,
    ACTIONS(176), 8,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_DOUBLE,
      sym_STRING_LITERAL_LONG_SINGLE_QUOTE,
      sym_STRING_LITERAL_LONG_QUOTE,
      sym_ANON,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(178), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1040] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(182), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1060] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(186), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1080] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(190), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1100] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(194), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(198), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(202), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(194), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(206), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 4,
      aux_sym__prefixID_token1,
      aux_sym__sparqlPrefix_token1,
      aux_sym__sparqlBase_token1,
      anon_sym_LBRACK,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_ATprefix,
      anon_sym_ATbase,
      anon_sym_LPAREN,
      sym_IRIREF,
      sym__PNAME_LN,
      sym_BLANK_NODE_LABEL,
      sym_ANON,
  [1240] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(216), 1,
      anon_sym_a,
    STATE(8), 1,
      sym_verb,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(24), 1,
      sym_iri,
    STATE(25), 1,
      sym_predicate,
    ACTIONS(214), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1273] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(216), 1,
      anon_sym_a,
    ACTIONS(218), 1,
      anon_sym_DOT,
    STATE(5), 1,
      sym_verb,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(24), 1,
      sym_iri,
    STATE(25), 1,
      sym_predicate,
    STATE(51), 1,
      sym_predicateObjectList,
  [1307] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(216), 1,
      anon_sym_a,
    STATE(5), 1,
      sym_verb,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(24), 1,
      sym_iri,
    STATE(25), 1,
      sym_predicate,
    STATE(56), 1,
      sym_predicateObjectList,
  [1338] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    ACTIONS(216), 1,
      anon_sym_a,
    STATE(5), 1,
      sym_verb,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(24), 1,
      sym_iri,
    STATE(25), 1,
      sym_predicate,
    STATE(55), 1,
      sym_predicateObjectList,
  [1369] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_objectList_repeat1,
    ACTIONS(220), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1384] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      aux_sym__prefixID_token1,
    ACTIONS(21), 1,
      sym_IRIREF,
    ACTIONS(23), 1,
      sym__PNAME_LN,
    STATE(13), 1,
      sym_PrefixedName,
    STATE(23), 1,
      sym_iri,
  [1403] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_objectList_repeat1,
    ACTIONS(224), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1418] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_objectList_repeat1,
    ACTIONS(229), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1433] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      aux_sym_predicateObjectList_repeat1,
    ACTIONS(231), 2,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1447] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_predicateObjectList_repeat1,
    ACTIONS(235), 2,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1461] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      aux_sym_predicateObjectList_repeat1,
    ACTIONS(240), 2,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      aux_sym__prefixID_token1,
      anon_sym_a,
    ACTIONS(244), 2,
      sym_IRIREF,
      sym__PNAME_LN,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 4,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_DOT,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_IRIREF,
  [1520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      aux_sym__prefixID_token1,
  [1527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_IRIREF,
  [1534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_DOT,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
  [1548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_DOT,
  [1555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_LANGTAG,
  [1562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_IRIREF,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
  [1576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_DOT,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      aux_sym__prefixID_token1,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_IRIREF,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 67,
  [SMALL_STATE(4)] = 134,
  [SMALL_STATE(5)] = 201,
  [SMALL_STATE(6)] = 267,
  [SMALL_STATE(7)] = 345,
  [SMALL_STATE(8)] = 423,
  [SMALL_STATE(9)] = 489,
  [SMALL_STATE(10)] = 552,
  [SMALL_STATE(11)] = 583,
  [SMALL_STATE(12)] = 618,
  [SMALL_STATE(13)] = 648,
  [SMALL_STATE(14)] = 678,
  [SMALL_STATE(15)] = 708,
  [SMALL_STATE(16)] = 738,
  [SMALL_STATE(17)] = 768,
  [SMALL_STATE(18)] = 798,
  [SMALL_STATE(19)] = 827,
  [SMALL_STATE(20)] = 856,
  [SMALL_STATE(21)] = 885,
  [SMALL_STATE(22)] = 914,
  [SMALL_STATE(23)] = 943,
  [SMALL_STATE(24)] = 972,
  [SMALL_STATE(25)] = 996,
  [SMALL_STATE(26)] = 1020,
  [SMALL_STATE(27)] = 1040,
  [SMALL_STATE(28)] = 1060,
  [SMALL_STATE(29)] = 1080,
  [SMALL_STATE(30)] = 1100,
  [SMALL_STATE(31)] = 1120,
  [SMALL_STATE(32)] = 1140,
  [SMALL_STATE(33)] = 1160,
  [SMALL_STATE(34)] = 1180,
  [SMALL_STATE(35)] = 1200,
  [SMALL_STATE(36)] = 1220,
  [SMALL_STATE(37)] = 1240,
  [SMALL_STATE(38)] = 1273,
  [SMALL_STATE(39)] = 1307,
  [SMALL_STATE(40)] = 1338,
  [SMALL_STATE(41)] = 1369,
  [SMALL_STATE(42)] = 1384,
  [SMALL_STATE(43)] = 1403,
  [SMALL_STATE(44)] = 1418,
  [SMALL_STATE(45)] = 1433,
  [SMALL_STATE(46)] = 1447,
  [SMALL_STATE(47)] = 1461,
  [SMALL_STATE(48)] = 1475,
  [SMALL_STATE(49)] = 1487,
  [SMALL_STATE(50)] = 1497,
  [SMALL_STATE(51)] = 1506,
  [SMALL_STATE(52)] = 1513,
  [SMALL_STATE(53)] = 1520,
  [SMALL_STATE(54)] = 1527,
  [SMALL_STATE(55)] = 1534,
  [SMALL_STATE(56)] = 1541,
  [SMALL_STATE(57)] = 1548,
  [SMALL_STATE(58)] = 1555,
  [SMALL_STATE(59)] = 1562,
  [SMALL_STATE(60)] = 1569,
  [SMALL_STATE(61)] = 1576,
  [SMALL_STATE(62)] = 1583,
  [SMALL_STATE(63)] = 1590,
  [SMALL_STATE(64)] = 1597,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_turtleDoc, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_turtleDoc, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_turtleDoc_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_String, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_String, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_RDFLiteral, 1, 0, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_RDFLiteral, 1, 0, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_PrefixedName, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_PrefixedName, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iri, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iri, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_collection, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collection, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_BlankNode, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_BlankNode, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_collection, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collection, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blankNodePropertyList, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blankNodePropertyList, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_BooleanLiteral, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_BooleanLiteral, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_RDFLiteral, 3, 0, 12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_RDFLiteral, 3, 0, 12),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_NumericLiteral, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_NumericLiteral, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_RDFLiteral, 3, 0, 11),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_RDFLiteral, 3, 0, 11),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verb, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verb, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sparqlBase, 2, 0, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sparqlBase, 2, 0, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base, 3, 0, 3),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__base, 3, 0, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1, 0, 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix, 1, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sparqlPrefix, 3, 0, 6),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sparqlPrefix, 3, 0, 6),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__prefixID, 4, 0, 6),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__prefixID, 4, 0, 6),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_base, 1, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_base, 1, 0, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicateObjectList_repeat1, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triples, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectList, 1, 0, 8),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_objectList_repeat1, 2, 0, 15),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_objectList_repeat1, 2, 0, 15), SHIFT_REPEAT(9),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objectList, 2, 0, 10),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicateObjectList, 2, 0, 7),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicateObjectList_repeat1, 2, 0, 13),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicateObjectList_repeat1, 2, 0, 13), SHIFT_REPEAT(37),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicateObjectList, 3, 0, 9),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_objectList_repeat1, 2, 0, 14),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicateObjectList_repeat1, 3, 0, 16),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triples, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_triples, 2, 0, 5),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_turtle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "turtle",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
